volumes:
  mongodb_data:

services:
  database:
    image: mongo:8
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb-replicaset.js:/docker-entrypoint-initdb.d/mongodb-replicaset.js
    environment:
      # MONGO_INITDB_ROOT_USERNAME: ps8
      # MONGO_INITDB_ROOT_PASSWORD: 734741ec1209b29040ac
      MONGO_INITDB_DATABASE: ps8

  gateway:
    build: .
    command: gateway
    restart: always
    environment:
      GAMESVC_ADDR: "gamesvc:8002"
      FILES_ADDR: "files:8001"
      AUTH_ADDR: "auth:8003"
      SOCIAL_ADDR: "social:8004"
    ports:
        - "8000:8000"

  gamesvc:
    build: .
    command: gamesvc
    restart: always
    env_file:
      - path: .env
        required: false
    environment:
      BOT_USERNAME: "Ane Trotro"
      DB_URL: "database?replicaSet=rs0&directConnection=true"

  files:
    build: .
    command: files
    restart: always

  auth:
    build: .
    command: auth
    restart: always
    environment:
      DB_URL: "database?replicaSet=rs0&directConnection=true"

  social:
    build: .
    command: social
    restart: always
    env_file:
      - path: .env
        required: false
    environment:
      BOT_USERNAME: "Ane Trotro"
      DB_URL: "database?replicaSet=rs0&directConnection=true"
