volumes:
  mongodb_data:

services:
  database:
    image: mongo:5
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ps8
      MONGO_INITDB_ROOT_PASSWORD: 734741ec1209b29040ac
      MONGO_INITDB_DATABASE: ps8

  gateway:
    build: .
    command: gateway
    environment:
      GAMESVC_ADDR: "gamesvc:8002"
      FILES_ADDR: "files:8001"
      AUTH_ADDR: "auth:8003"
    ports:
        - "8000:8000"

  gamesvc:
    build: .
    command: gamesvc

  files:
    build: .
    command: files

  auth:
    build: .
    command: auth
