volumes:
  mongodb_data:

services:
  database:
    image: mongo:5
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ps8
      MONGO_INITDB_ROOT_PASSWORD: 734741ec1209b29040ac
      MONGO_INITDB_DATABASE: ps8

  gateway:
    build: .
    command: gateway
    restart: always
    environment:
      GAMESVC_ADDR: "gamesvc:8002"
      FILES_ADDR: "files:8001"
      AUTH_ADDR: "auth:8003"
    ports:
        - "8000:8000"

  gamesvc:
    build: .
    command: gamesvc
    restart: always

  files:
    build: .
    command: files
    restart: always

  auth:
    build: .
    command: auth
    restart: always
    environment:
      DB_USER: "ps8"
      DB_PASSWORD: "734741ec1209b29040ac"
      DB_URL: "database"
